create database CaseStudy
use CaseStudy
select * from [dbo].[Customer]
select * from [dbo].[prod_cat_info]
select * from Transactions

--#DATA PREPARATION AND UNDERSTANDING
--01 What is the total number of rows in each of the 3 tables in the database

select (select count(*) from [prod_cat_info]) as Prod_cat,
(select count(*) from [Transactions] as Transact),
(select count(*) from  [dbo].[Customer]

--02 What is the total number of transactions that have a return

select 
count(*)  as Total_Rows from [dbo].[Transactions]
where [total_amt] like '-%' 

--03 As you would have noticed, the dates provided across the datasets are not in a
-- correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.

SELECT FORMAT(DOB, 'dd-MM-yyyy') AS formatted_date
FROM Customer;
select Format([tran_date],'dd-MM-yyyy') as Format_date
from [dbo].[Transactions] 


--04 What is the time range of the transaction data available for analysis?
-- Show the output in number of days, months and years simultaneously in different columns

select 
DATEDIFF(DAY, min(tran_date),max(tran_date)) as Days,
DATEDIFF(MONTH, min(tran_date),max(tran_date)) as Months,
DATEDIFF(YEAR, min(tran_date),max(tran_date)) as Years
from [dbo].[Transactions]

--05 Which product category does the sub-category “DIY” belong to

select
prod_cat
from [dbo].[prod_cat_info] 
where prod_subcat='DIY'


--#DATA ANALYSIS
--01 Which channel is most frequently used for transactions

SELECT top 1 Store_type,count([transaction_id]) as Trans
FROM Transactions
group by Store_type
ORDER BY count([transaction_id])  Desc 

--02 What is the count of Male and Female customers in the database

select Gender,count(*) as Total_count
from [dbo].[Customer]
where Gender in ('M','F')
group by Gender

--03 From which city do we have the maximum number of customers and how many

select top 1 city_code,count(*) as Customers
from [dbo].[Customer]
group by city_code
order by Customers desc 

--04 How many sub-categories are there under the Books category

select prod_cat,count([prod_subcat]) as Total_subcat
from [dbo].[prod_cat_info]
where  prod_cat='Books'
group by prod_cat 

--05 What is the maximum quantity of products ever ordered

select Max(Qty) as Max_qty
from [dbo].[Transactions] t

--06 What is the net total revenue generated in categories Electronics and Books

select [prod_cat],sum([total_amt]) as Total_revenue
from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on p.[prod_cat_code] =t.[prod_cat_code]
where [prod_cat] in ( 'Electronics','Books') 
group by [prod_cat]

--07 How many customers have >10 transactions with us, excluding returns

select count([customer_Id]) as Total_Customer
from [dbo].[Customer] where [customer_Id] in
(select cust_id
from Transactions t
inner join [dbo].[Customer] C on C.[customer_Id]=t.[cust_id]
where [total_amt] not like '-%'
group by [cust_id]
having count(transaction_id)>10 )

--08 What is the combined revenue earned from the “Electronics” & “Clothing" categories, from “Flagship stores”
select sum(total_amt) as Combined_revenue
from Transactions T
inner join [dbo].[prod_cat_info] p on p.prod_cat_code=T.prod_cat_code
and T.[prod_subcat_code]=p.prod_sub_cat_code
where prod_cat in ('Electronics','Clothing') and Store_type='Flagship store' 

--09 What is the total revenue generated from “Male” customers in “Electronics” category

select  p.prod_subcat,p.prod_cat,sum(total_amt) as Total_revenue
from Customer C
left  join Transactions T on T.[cust_id]=C.customer_Id
left join prod_cat_info p on p.[prod_cat_code]=T.[prod_cat_code]
where Gender like 'M%'
group by  p.prod_subcat,p.prod_cat
Having prod_cat='Electronics' 

--10  What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales

select top 5 p.prod_subcat,(sum([total_amt])/(select sum([total_amt])  from [dbo].[Transactions]))*100 as per_sales,
(count(case when [total_amt]<0 then [total_amt] else null end)/sum([total_amt]))*100 as per_returns
from [dbo].[prod_cat_info] p
inner join [dbo].[Transactions] T on T.[prod_cat_code]=p.[prod_cat_code] AND T.[prod_subcat_code]=p.[prod_sub_cat_code]
group by p.prod_subcat
order by sum([total_amt]) desc

--11 For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction
-- date available in the data

SELECT cust_id,
    SUM([total_amt]) AS net_total_revenue
	from [dbo].[Transactions]
	where cust_id in
	(SELECT  [customer_Id] FROM Customer
 where   DATEDIFF(YEAR,convert(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
	AND convert(DATE,tran_date,103) between dateadd(day,-30,
	(select max(convert(DATE,tran_date,103)) from [dbo].[Transactions]))
	AND (select max(convert(DATE,tran_date,103)) from [dbo].[Transactions])
	group by cust_id

--12  Which product category has seen the max value of returns in the last 3 months of transactions

	SELECT 
   [prod_cat],
    SUM([total_amt]) AS total_returns
FROM 
    [dbo].[prod_cat_info] p
	inner join Transactions T on T.[prod_cat_code]=p.[prod_cat_code]
	WHERE [total_amt] < 0 and convert(DATE,tran_date,103) between dateadd(month,-3,
	(select max(convert(DATE,tran_date,103)) from [dbo].[Transactions]))
	AND (select max(convert(DATE,tran_date,103)) from [dbo].[Transactions])
GROUP BY 
    [prod_cat]
ORDER BY 
    total_returns DESC 

--13 Which store-type sells the maximum products; by value of sales amount and by quantity sold

select  top 1 Store_type,sum([Qty]) as total_Qty,sum([total_amt]) as Total_Sale
	from [dbo].[Transactions]
group by  Store_type
order by  total_Qty desc 

--14  What are the categories for which average revenue is above the overall average.

select  prod_cat,avg([total_amt]) as Avg_revenue
from Transactions T
inner join [dbo].[prod_cat_info] p on p.[prod_cat_code]=T.[prod_cat_code]
group by prod_cat
having avg([total_amt]) > (select avg([total_amt]) from Transactions) 

--15 Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold

select top 5 [prod_cat],[prod_subcat],avg([total_amt]) as avg_rev,
sum([total_amt]) as tot_rev
from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info] p on p.[prod_cat_code]=t.[prod_cat_code] and p.[prod_sub_cat_code]=t.[prod_subcat_code]
where [prod_cat] in
(select top 5 [prod_cat] from [dbo].[Transactions] t
inner join [dbo].[prod_cat_info]p on p.[prod_cat_code]=t.[prod_cat_code] 
group by [prod_cat]
order by sum(Qty) desc )
group by [prod_cat],[prod_subcat]







